### PR TITLE
Changes top of 'R' slightly to match suggestion in issue #5

### PR DESCRIPTION
**Pull request by jonrandy**

### CODE REVIEW

**Comment by GianlucaGuarini** [comment]
@nibushibu could you please have a look at it? thank you

**Comment by nibushibu** [comment]
Thanks for the suggestions.

In response to the suggestions, I wanted to make some more corrections.

The difference seems to be an optical illusion, so I felt that the amount of change was a little too large.
Sorry after the suggestions, can you see my modified ideas?

Since I am not good at English, the adjustments are shown in the figure below.
I think that the reason for the slight deviation is also the amount of rounded corners at the right end.

@jonrandy How is it? Did your logo look improve?

riotjs-logo-fixed

[riotjs-logo-fixed.pdf](https://github.com/riot/logo/files/4070634/riotjs-logo-fixed.pdf)

**Comment by jonrandy** [comment]
I think that rounding really helps. It achieves a similar effect to what I had in mind. The change I made was admittedly probably a little too much.

I think your change fixes the issue nicely 👍

**Comment by nibushibu** [comment]
Thank you for your quick response.

I have created a new pull request #7

**Pull request closed without merging**
