### PR TITLE
Added icons and logos for branding to several modules.

### PR DESCRIPTION
**Pull request by nibushibu**
As the title says. #8

Since the number of files has increased, I have also organized the existing data into folders.

### CODE REVIEW

**Comment by nibushibu** [comment]
The design concept of the added logo is as follows.

ovservable-logo-concept

animore-logo-concept

route-logo-concept

ssr-logo-concept

cli-logo-concept

lazy-logo-concept

hot-reload-logo-concept

custom-elements-logo-concept

**Review by GianlucaGuarini — CHANGES_REQUESTED** [review]
Thank you @nibushibu you did an incredible job! Could you please just update the `@riotjs/lazy` logo? The `Z` reminds me too much the current brutal war 🇷🇺 is fighting in 🇺🇦 , prefer probably a hourglass or something similar for it.

**Comment by nibushibu** [comment]
@GianlucaGuarini  Oops, you are right.
I had foolishly forgotten to consider your point.
The hourglass is a great idea! I will reconsider.

**Comment by nibushibu** [comment]
@GianlucaGuarini Hi, thank you for your patience.
I redesigned the logo for the lazy module based on your suggestions. I feel the "hourglass" idea you suggested is a better motif than my first design.👍 I used the negative space between the two "L"s to represent an hourglass.
And I improved some other logo for unification of design.

riotjs-modules-logo-2022-07-09-1652

**Review by GianlucaGuarini — APPROVED** [review]

**Comment by GianlucaGuarini** [comment]
@nibushibu thank you you did a great work. Please feel free to submit your expense here https://opencollective.com/riot I will be happy to pay for your work.

**Pull request merged**
